User.create!([
  {first_name: "Arthur ", last_name: "Wellesley", email: "dukewellington@gmx.de", encrypted_password: "$2a$11$INHxnwlVcvnuGLOcWB4qRuOyf.cx8qmpn7Jprv35h4Uu5mRP8BRRS", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, admin: true},
  {first_name: "Peter", last_name: "Pupsmann", email: "andreas@admin.de", encrypted_password: "$2a$11$njY4lPtnaIFRirY2S5PlRuD8uxROajgipFV0DfnVfy2cvNkZAtuJC", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, admin: false},
  {first_name: "Arsch", last_name: "Kopp", email: "arschkopf@fookoonudel.com", encrypted_password: "$2a$11$9aUBzC4gSpWA5mycHlEjPuv4BClXuydh.S5aBjB6bjFkZ.bTn1z4a", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, admin: false},
  {first_name: "Furzklaus", last_name: "Pupsmann", email: "johndoe@randomuser.com", encrypted_password: "$2a$11$XMRzTdXWjO/yfZMVbWMC9.DTO7Uy8u4aerTHuhBG32A.VZXMwMVki", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, admin: false}
])
Cart.create!([
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: 1},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil},
  {user_id: 63},
  {user_id: nil},
  {user_id: nil},
  {user_id: nil}
])
Comment.create!([
  {user_id: 1, body: "nice", rating: 4, product_id: 1},
  {user_id: 1, body: "What a great bike! ", rating: 5, product_id: 1},
  {user_id: 1, body: "This bike sucks!!", rating: 0, product_id: 1},
  {user_id: 1, body: "This Bicycle is bike is an absolutely wonderful piece of machinery. Marvelous! Spectacular!", rating: 5, product_id: 1},
  {user_id: 1, body: "This thing is way to fast. Not my cup of coffee.", rating: 2, product_id: 4},
  {user_id: 1, body: "This Bike is the shit! Yeah!", rating: 5, product_id: 4},
  {user_id: 1, body: "Faster than lightning! I'm liking it!!!", rating: 5, product_id: 3},
  {user_id: 1, body: "It doesn't even have pedals.", rating: nil, product_id: 3},
  {user_id: 65, body: "AJAX", rating: 1, product_id: 5},
  {user_id: 65, body: "Reload manually?", rating: 2, product_id: 5},
  {user_id: 1, body: "New Review", rating: 3, product_id: 5},
  {user_id: 1, body: "why", rating: 4, product_id: 5},
  {user_id: 1, body: "not working?", rating: 4, product_id: 5},
  {user_id: 1, body: "comment on this bike", rating: 5, product_id: 4},
  {user_id: 1, body: "Product channel is streaming from Product 1.", rating: 1, product_id: 1},
  {user_id: 1, body: "Product channel is streaming from Product 1.", rating: 1, product_id: 1},
  {user_id: 1, body: "Yeiyaeh", rating: 1, product_id: 1},
  {user_id: 1, body: "QQQQQQQQQQQQQQQQ", rating: 3, product_id: 1},
  {user_id: 1, body: "aaaaaaaaaaaaaa", rating: 4, product_id: 1},
  {user_id: 1, body: "I want to befart you full, yeah?", rating: 1, product_id: 1},
  {user_id: 1, body: "why cannot working now?", rating: 4, product_id: 5},
  {user_id: 1, body: "pupsfisch", rating: 1, product_id: 5},
  {user_id: 1, body: "Oh man!!", rating: 1, product_id: 1},
  {user_id: 1, body: "puparsch!", rating: nil, product_id: 1},
  {user_id: 1, body: "test", rating: 1, product_id: 6},
  {user_id: 1, body: "5", rating: 5, product_id: 6},
  {user_id: 1, body: "geilie!", rating: 5, product_id: 1}
])
LineItem.create!([
  {cart_id: 48, quantity: 1, product_id: 1},
  {cart_id: 78, quantity: 1, product_id: 1},
  {cart_id: 79, quantity: 3, product_id: 1},
  {cart_id: 82, quantity: 1, product_id: 1},
  {cart_id: 87, quantity: 1, product_id: 1},
  {cart_id: 89, quantity: 1, product_id: 1},
  {cart_id: 90, quantity: 1, product_id: 1},
  {cart_id: 91, quantity: 1, product_id: 1},
  {cart_id: 92, quantity: 1, product_id: 1},
  {cart_id: 94, quantity: 3, product_id: 1},
  {cart_id: 98, quantity: 1, product_id: 1},
  {cart_id: 107, quantity: 1, product_id: 1},
  {cart_id: 110, quantity: 2, product_id: 1},
  {cart_id: 111, quantity: 1, product_id: 1},
  {cart_id: 112, quantity: 1, product_id: 1},
  {cart_id: 113, quantity: 1, product_id: 1},
  {cart_id: 114, quantity: 1, product_id: 1},
  {cart_id: 115, quantity: 1, product_id: 3},
  {cart_id: 116, quantity: 1, product_id: 1},
  {cart_id: 117, quantity: 1, product_id: 1},
  {cart_id: 118, quantity: 1, product_id: 1},
  {cart_id: 119, quantity: 1, product_id: 1},
  {cart_id: 120, quantity: 1, product_id: 1},
  {cart_id: 122, quantity: 1, product_id: 1},
  {cart_id: 123, quantity: 1, product_id: 1},
  {cart_id: 124, quantity: 1, product_id: 1},
  {cart_id: 126, quantity: 2, product_id: 1},
  {cart_id: 126, quantity: 1, product_id: 3},
  {cart_id: 130, quantity: 1, product_id: 1},
  {cart_id: 131, quantity: 1, product_id: 1},
  {cart_id: 134, quantity: 1, product_id: 1},
  {cart_id: 138, quantity: 1, product_id: 1},
  {cart_id: 141, quantity: 1, product_id: 1},
  {cart_id: 142, quantity: 1, product_id: 1},
  {cart_id: 143, quantity: 1, product_id: 1},
  {cart_id: 145, quantity: 1, product_id: 1},
  {cart_id: 162, quantity: 1, product_id: 1},
  {cart_id: 174, quantity: 1, product_id: 1},
  {cart_id: 179, quantity: 1, product_id: 1},
  {cart_id: 183, quantity: 1, product_id: 1},
  {cart_id: 126, quantity: 1, product_id: 5},
  {cart_id: 190, quantity: 1, product_id: 1},
  {cart_id: 195, quantity: 1, product_id: 1},
  {cart_id: 206, quantity: 1, product_id: 1},
  {cart_id: 211, quantity: 1, product_id: 1},
  {cart_id: 224, quantity: 1, product_id: 1},
  {cart_id: 227, quantity: 1, product_id: 1},
  {cart_id: 228, quantity: 1, product_id: 1},
  {cart_id: 231, quantity: 1, product_id: 1},
  {cart_id: 233, quantity: 1, product_id: 1},
  {cart_id: 234, quantity: 1, product_id: 1},
  {cart_id: 240, quantity: 1, product_id: 1},
  {cart_id: 241, quantity: 1, product_id: 1},
  {cart_id: 242, quantity: 1, product_id: 1},
  {cart_id: 243, quantity: 1, product_id: 1},
  {cart_id: 249, quantity: 1, product_id: 1},
  {cart_id: 254, quantity: 1, product_id: 1},
  {cart_id: 262, quantity: 1, product_id: 1},
  {cart_id: 269, quantity: 1, product_id: 1},
  {cart_id: 274, quantity: 1, product_id: 1},
  {cart_id: 263, quantity: 1, product_id: 1},
  {cart_id: 277, quantity: 1, product_id: 1},
  {cart_id: 281, quantity: 1, product_id: 1},
  {cart_id: 290, quantity: 1, product_id: 1},
  {cart_id: 295, quantity: 1, product_id: 1},
  {cart_id: 305, quantity: 1, product_id: 1},
  {cart_id: 313, quantity: 1, product_id: 1},
  {cart_id: 322, quantity: 1, product_id: 1},
  {cart_id: 325, quantity: 1, product_id: 1},
  {cart_id: 331, quantity: 1, product_id: 1},
  {cart_id: 333, quantity: 1, product_id: 1},
  {cart_id: 338, quantity: 1, product_id: 1},
  {cart_id: 341, quantity: 1, product_id: 1},
  {cart_id: 347, quantity: 1, product_id: 1},
  {cart_id: 352, quantity: 1, product_id: 1},
  {cart_id: 357, quantity: 1, product_id: 1},
  {cart_id: 362, quantity: 1, product_id: 1},
  {cart_id: 365, quantity: 1, product_id: 1},
  {cart_id: 366, quantity: 1, product_id: 1},
  {cart_id: 367, quantity: 1, product_id: 1},
  {cart_id: 368, quantity: 1, product_id: 1},
  {cart_id: 371, quantity: 1, product_id: 1},
  {cart_id: 371, quantity: 1, product_id: 3}
])
Order.create!([
  {user_id: 1, product_id: 1, total: 10.0},
  {user_id: 1, product_id: 3, total: 5.0},
  {user_id: 1, product_id: 1, total: 949.95},
  {user_id: 1, product_id: 1, total: 949.95},
  {user_id: 1, product_id: 1, total: 949.95},
  {user_id: 63, product_id: 1, total: 949.95},
  {user_id: 63, product_id: 1, total: 949.95},
  {user_id: 63, product_id: 1, total: 949.95},
  {user_id: 63, product_id: 1, total: 949.95},
  {user_id: 63, product_id: 1, total: 949.95},
  {user_id: 63, product_id: 1, total: 949.95},
  {user_id: 63, product_id: 1, total: 949.95},
  {user_id: 1, product_id: 1, total: 949.95},
  {user_id: 67, product_id: 1, total: 949.95},
  {user_id: 67, product_id: 1, total: 949.95},
  {user_id: 69, product_id: 5, total: 2499.95}
])
Product.create!([
  {name: "Mountain Challenger", description: "Sleek yet Robust - Perfect for high speed downhill rides of the breakneck variety!", image_url: "adventure-beach-bicycle-462036.jpg", colour: "black", price: "949.95"},
  {name: "Elegant Racer", description: "Rapid and Stylish - Perfect for covering long distances at high velocity!", image_url: "mikkel-bech-748940-unsplash.jpg", colour: "black white", price: "1499.99"},
  {name: "Single Speed Beauty", description: "Quick and Graceful - Perfect for riding around town in style. Discover the Hipster in you!", image_url: "robert-bye-200735-unsplash.jpg", colour: "white", price: "949.99"},
  {name: "Old Time Standard", description: "Unique and Daring - Perfect for the proper aspirer with a vintage kind of taste. ", image_url: "wheel-3184641_1920.jpg", colour: "black", price: "2499.95"},
  {name: "Vintage Bike", description: "", image_url: "race_bike.png", colour: "", price: "949.5"}
])
